# Generated by Django 2.1.4 on 2019-02-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
