# Generated by Django 2.1.4 on 2019-02-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sin', '0002_auto_20190226_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='age',
        ),
    ]
