# Generated by Django 2.1.4 on 2019-02-28 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sin', '0005_product_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(max_length=100)),
                ('is_guarantee', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
            ],
        ),
        migrations.AddField(
            model_name='fixservice',
            name='fix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sin.Service'),
        ),
        migrations.AddField(
            model_name='fixservice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sin.Product'),
        ),
    ]
