# Generated by Django 2.1.4 on 2019-03-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sin', '0011_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='type_report',
            field=models.IntegerField(default=0),
        ),
    ]
