# Generated by Django 2.1.4 on 2019-03-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sin', '0013_bill_productcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
